### ISSUE TITLE
Browser not showing images

### ISSUE THREAD

**Issue by xyangwu** [activityMonitoring/oxford-wearable-camera-browser#27]
```
> npm start
Electron could not be found. No hard resets for you!

start
all resizing done!
ipc IMAGE_DIR C:\Users\MyName\OxfordImageBrowser\images\
ipc ANNOTATION_DIR C:\Users\MyName\OxfordImageBrowser\annotation\
ipc SCHEMA_DIR C:\Users\MyName\OxfordImageBrowser\schema\
resize_status
```

The warning message `"Electron could not be found. No hard resets for you!"` was printed. The Oxford Image Browser window was displayed though.
Images are not shown in window:
<img width="756" alt="window" src="https://user-images.githubusercontent.com/48620311/194488830-8641d98e-c351-4e28-889b-4caffcd23c0b.png">

System Info:
Windows 10
node v12.13.1
electron v1.8.8

**Comment by xyangwu** [comment]
Hi, guess I got the reason why images are not displayed in the browser😅. Two resized copies of original images should be placed in directories `medium` and `thumbnail`, as noted in [fileInput.md](https://github.com/OxWearables/oxford-wearable-camera-browser/blob/master/fileInput.md).

**Comment by xyangwu** [comment]
Also note that there is no `convert` command on Windows which is available on Linux. ImageMagick can do resizing with a tool called convert. After ImageMagick installed, adding `magick`  at the front of line 11 in [create_thumbnails.sh](https://github.com/OxWearables/oxford-wearable-camera-browser/blob/master/utilities/create_thumbnails.sh) will make it work:
```
magick convert -resize $size $i $newDirName/$i
```

**Comment by aidendoherty** [comment]
Many thanks @xyangwu !
